---
- name: Uninstall Old Docker Versions
  apt:
   name: "{{ item }}"
   state: absent
  with_items:
   - docker
   - docker-engine
   - docker.io

- name: Install Packages to allow apt to use repository over HTTPs
  apt:
   name: "{{ item }}"
   state: present
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common

- name: Add Docker's Official CPG Key
  apt_key:
   id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present

- name: Get lsb_release
  shell: lsb_release -cs
  register: lsb_release

- name: Setup stable repository
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
   state: present
   update_cache: yes
  ignore_errors: true

- name: Install Docker
  apt:
   name: docker-ce
   state: present
...
